-- =====================================================================
-- JARVIS Phase 1.0 - Migration 0014 - Befuellung des Werkzeugregisters
--
-- ERZEUGT durch tools/render_tool_registry.py. Nicht von Hand bearbeiten.
-- Quelle:
--   spec/phase-0/jarvis-phase-0/registry/tool_registry.json
--   spec/phase-1/jarvis-phase-1/registry/tool_registry_phase1.json
--
-- Wiederholbar: Vorhandene Eintraege werden nie ueberschrieben. Der
-- Freigabestatus in der Datenbank bleibt erhalten. Weicht die Definition
-- einer bereits geladenen Version ab, bricht der Lauf ab: Eine geaenderte
-- Definition erfordert eine neue Version.
-- Werkzeuge: 14
-- =====================================================================

INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('storage_gdrive.move_file', '1.0.0', 'storage_gdrive', 'write', 'internal', 'A', 'reversible', 'storage_gdrive.move_file', ARRAY['privat']::text[], true, ARRAY['readback']::text[], NULL, 60, true, 'draft', '{"owner": "rolf", "purpose": "Datei in den kontextbezogenen Zielordner verschieben und umbenennen.", "tool_id": "storage_gdrive.move_file", "version": "1.0.0", "evidence": {"limitation": null, "required_types": ["file_ref", "state_readback"], "accepted_methods": ["readback"], "readback_supported": true, "verify_delay_seconds": 5, "deferred_check_after_hours": null}, "operation": "write", "adapter_id": "storage_gdrive", "rate_limit": null, "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": "content_hash", "native_support": false}, "display_name": "Datei ablegen", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "rate_limited", "timeout"]}, "side_effects": "Die Datei liegt danach an einem anderen Ort und traegt einen anderen Namen.", "undo_tool_id": "storage_gdrive.move_file", "reversibility": "reversible", "external_effect": "internal", "timeout_seconds": 60, "allowed_contexts": ["privat"], "input_schema_ref": "schemas/tools/storage_gdrive.move_file.input.json", "dry_run_supported": true, "output_schema_ref": "schemas/tools/storage_gdrive.move_file.output.json", "risk_class_default": "A", "required_permissions": ["Datei lesen", "Datei verschieben", "Datei umbenennen"]}'::jsonb, '3b5c4ef233920e50fcd409d62ffca18bd67a610f0386b6e68e7cc66380c95f34', 'spec/phase-0/jarvis-phase-0/registry/tool_registry.json', 'b97208de94bbedfc0b00ef8e99ba749cabd766e6f85f48e6a933dc972761e613') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('tasks_internal.create_task', '1.0.0', 'tasks_internal', 'write', 'internal', 'A', 'reversible', 'tasks_internal.cancel_task', ARRAY['privat', 'arbeitgeber_visolva']::text[], true, ARRAY['readback']::text[], NULL, 30, true, 'draft', '{"owner": "rolf", "purpose": "Aufgabe im JARVIS-Aufgabenregister anlegen.", "tool_id": "tasks_internal.create_task", "version": "1.0.0", "evidence": {"limitation": null, "required_types": ["task_ref"], "accepted_methods": ["readback"], "readback_supported": true, "verify_delay_seconds": 0, "deferred_check_after_hours": null}, "operation": "write", "adapter_id": "tasks_internal", "rate_limit": null, "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": null, "native_support": false}, "display_name": "Aufgabe anlegen", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "timeout"]}, "side_effects": "Ein neuer Aufgabendatensatz entsteht.", "undo_tool_id": "tasks_internal.cancel_task", "reversibility": "reversible", "external_effect": "internal", "timeout_seconds": 30, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/task.schema.json", "dry_run_supported": true, "output_schema_ref": "schemas/task.schema.json", "risk_class_default": "A", "required_permissions": ["Schreibrecht im Kontextschema"]}'::jsonb, '7f7ffd57979954afa94bb742f3958c65f7f9e46067d2b00907c02160e40fd1ac', 'spec/phase-0/jarvis-phase-0/registry/tool_registry.json', 'b97208de94bbedfc0b00ef8e99ba749cabd766e6f85f48e6a933dc972761e613') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('mail_default.send_message', '1.0.0', 'mail_default', 'write', 'external_recipient', 'C', 'irreversible', NULL, ARRAY['privat', 'arbeitgeber_visolva']::text[], true, ARRAY['readback']::text[], NULL, 60, true, 'draft', '{"owner": "rolf", "purpose": "Individuelle oder freigegebene E-Mail versenden.", "tool_id": "mail_default.send_message", "version": "1.0.0", "evidence": {"limitation": null, "required_types": ["message_ref"], "accepted_methods": ["readback"], "readback_supported": true, "verify_delay_seconds": 15, "deferred_check_after_hours": null}, "operation": "write", "adapter_id": "mail_default", "rate_limit": null, "idempotency": {"strategy": "db_plus_provider", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": "content_fingerprint", "native_support": false}, "display_name": "E-Mail versenden", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "timeout", "rate_limited"]}, "side_effects": "Eine Nachricht verlaesst das System und erreicht einen externen Empfaenger.", "undo_tool_id": null, "reversibility": "irreversible", "external_effect": "external_recipient", "timeout_seconds": 60, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/tools/mail_default.send_message.input.json", "dry_run_supported": true, "output_schema_ref": "schemas/tools/mail_default.send_message.output.json", "risk_class_default": "C", "required_permissions": ["Nachricht senden", "Ordner Gesendet lesen"]}'::jsonb, 'bddb2305ff17cf0f5f470d597ffd2fb8ac6e73f339655477525fc0effa50c4ea', 'spec/phase-0/jarvis-phase-0/registry/tool_registry.json', 'b97208de94bbedfc0b00ef8e99ba749cabd766e6f85f48e6a933dc972761e613') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('messaging_superchat.send_template_message', '1.0.0', 'messaging_superchat', 'write', 'external_recipient', 'B', 'irreversible', NULL, ARRAY['arbeitgeber_visolva']::text[], false, ARRAY['provider_message_id', 'delivery_receipt', 'recipient_reply']::text[], 'Der Anbieter stellt keinen Lesezugriff auf die versendete Nachricht bereit. Die Anbieter-ID belegt die Annahme des Auftrags und die Zustellquittung die Auslieferung an das Endgeraet, nicht jedoch, dass der Empfaenger die Nachricht gelesen oder inhaltlich verstanden hat.', 45, false, 'draft', '{"owner": "rolf", "purpose": "Freigegebene Standardnachricht ueber den Messenger-Kanal senden.", "tool_id": "messaging_superchat.send_template_message", "version": "1.0.0", "evidence": {"limitation": "Der Anbieter stellt keinen Lesezugriff auf die versendete Nachricht bereit. Die Anbieter-ID belegt die Annahme des Auftrags und die Zustellquittung die Auslieferung an das Endgeraet, nicht jedoch, dass der Empfaenger die Nachricht gelesen oder inhaltlich verstanden hat.", "required_types": ["provider_id", "delivery_receipt"], "accepted_methods": ["provider_message_id", "delivery_receipt", "recipient_reply"], "readback_supported": false, "verify_delay_seconds": 30, "deferred_check_after_hours": 24}, "operation": "write", "adapter_id": "messaging_superchat", "rate_limit": "60/Stunde", "idempotency": {"strategy": "db_plus_provider", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": "content_fingerprint", "native_support": true}, "display_name": "Standardnachricht ueber Messenger senden", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "timeout", "rate_limited"]}, "side_effects": "Eine Nachricht wird an den Anbieter uebergeben und an einen externen Empfaenger zugestellt.", "undo_tool_id": null, "reversibility": "irreversible", "external_effect": "external_recipient", "timeout_seconds": 45, "allowed_contexts": ["arbeitgeber_visolva"], "input_schema_ref": "schemas/tools/messaging_superchat.send_template_message.input.json", "dry_run_supported": false, "output_schema_ref": "schemas/tools/messaging_superchat.send_template_message.output.json", "risk_class_default": "B", "required_permissions": ["Nachricht senden"]}'::jsonb, '8cded196683889056b0a0fe4e8e52cfedfe16d6e1dca10f820ecdf9e4694caec', 'spec/phase-0/jarvis-phase-0/registry/tool_registry.json', 'b97208de94bbedfc0b00ef8e99ba749cabd766e6f85f48e6a933dc972761e613') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('approval_email.request_decision', '1.0.0', 'approval_email', 'write', 'internal', 'A', 'reversible', 'approval_email.revoke_request', ARRAY['privat', 'arbeitgeber_visolva']::text[], true, ARRAY['readback']::text[], NULL, 30, true, 'draft', '{"owner": "rolf", "purpose": "Freigabeanforderung mit signiertem Einmal-Link an Rolf senden.", "tool_id": "approval_email.request_decision", "version": "1.0.0", "evidence": {"limitation": null, "required_types": ["message_ref"], "accepted_methods": ["readback"], "readback_supported": true, "verify_delay_seconds": 15, "deferred_check_after_hours": null}, "operation": "write", "adapter_id": "approval_email", "rate_limit": null, "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": "action_fingerprint", "native_support": false}, "display_name": "Freigabe anfordern", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "timeout"]}, "side_effects": "Rolf erhaelt eine Entscheidungsanfrage. Die freizugebende Aktion selbst bleibt unveraendert.", "undo_tool_id": "approval_email.revoke_request", "reversibility": "reversible", "external_effect": "internal", "timeout_seconds": 30, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/approval.schema.json", "dry_run_supported": true, "output_schema_ref": "schemas/approval.schema.json", "risk_class_default": "A", "required_permissions": ["Nachricht senden", "Ordner Gesendet lesen"]}'::jsonb, 'd259ab39ff01de0aa7a67f0f1ef4e6c48fceb5c8bc8af4ccb6b14ee5c5e8fc6d', 'spec/phase-0/jarvis-phase-0/registry/tool_registry.json', 'b97208de94bbedfc0b00ef8e99ba749cabd766e6f85f48e6a933dc972761e613') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('storage_gdrive.get_file', '1.0.0', 'storage_gdrive', 'read', 'none', 'A', 'reversible', NULL, ARRAY['privat', 'arbeitgeber_visolva']::text[], false, ARRAY['provider_status']::text[], 'Leseoperation ohne Zustandsaenderung. Der Nachweis belegt die erfolgreiche Antwort des Speicherdienstes einschliesslich Pruefsumme, nicht eine Veraenderung in der Welt.', 120, true, 'draft', '{"owner": "rolf", "purpose": "Originaldatei und ihre Metadaten aus dem kontextbezogenen Speicher lesen.", "tool_id": "storage_gdrive.get_file", "version": "1.0.0", "evidence": {"limitation": "Leseoperation ohne Zustandsaenderung. Der Nachweis belegt die erfolgreiche Antwort des Speicherdienstes einschliesslich Pruefsumme, nicht eine Veraenderung in der Welt.", "required_types": ["provider_status"], "accepted_methods": ["provider_status"], "readback_supported": false, "verify_delay_seconds": 0, "deferred_check_after_hours": null}, "operation": "read", "adapter_id": "storage_gdrive", "rate_limit": null, "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": null, "native_support": false}, "display_name": "Datei lesen", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "rate_limited", "timeout"]}, "side_effects": "Keine. Reine Leseoperation.", "undo_tool_id": null, "reversibility": "reversible", "external_effect": "none", "timeout_seconds": 120, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/tools/storage_gdrive.get_file.input.json", "dry_run_supported": true, "output_schema_ref": "schemas/tools/storage_gdrive.get_file.output.json", "risk_class_default": "A", "required_permissions": ["Datei lesen", "Metadaten lesen"]}'::jsonb, '02372a67f50f263bd052c2e6ccc96b7e4853c49b290a95a3b7a3eed16717561b', 'spec/phase-1/jarvis-phase-1/registry/tool_registry_phase1.json', '2aea6dc8246e518e070f91480e890c2b7d76d538e6a6420ae4c5e1f3667d3621') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('ocr_default.analyze_document', '1.0.0', 'ocr_default', 'read', 'none', 'A', 'reversible', NULL, ARRAY['privat', 'arbeitgeber_visolva']::text[], false, ARRAY['provider_status']::text[], 'Der Nachweis belegt, dass der Dienst ein Ergebnis zum uebermittelten Inhaltshash geliefert hat. Er belegt nicht die inhaltliche Richtigkeit der Texterkennung; diese wird ueber Konfidenz- und Feldregeln bewertet.', 300, false, 'draft', '{"owner": "rolf", "purpose": "Volltext, Seitenstruktur, Tabellen und Feldkandidaten mit Konfidenz und Positionsbezug erfassen.", "tool_id": "ocr_default.analyze_document", "version": "1.0.0", "evidence": {"limitation": "Der Nachweis belegt, dass der Dienst ein Ergebnis zum uebermittelten Inhaltshash geliefert hat. Er belegt nicht die inhaltliche Richtigkeit der Texterkennung; diese wird ueber Konfidenz- und Feldregeln bewertet.", "required_types": ["provider_status", "content_hash"], "accepted_methods": ["provider_status"], "readback_supported": false, "verify_delay_seconds": 0, "deferred_check_after_hours": null}, "operation": "read", "adapter_id": "ocr_default", "rate_limit": "600/Stunde", "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": "content_hash", "native_support": false}, "display_name": "Dokument technisch erfassen", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "rate_limited", "timeout", "dependency_unavailable"]}, "side_effects": "Das Dokument wird an einen externen Analysedienst uebermittelt. Es entsteht keine Veraenderung im Quellsystem.", "undo_tool_id": null, "reversibility": "reversible", "external_effect": "none", "timeout_seconds": 300, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/tools/ocr_default.analyze_document.input.json", "dry_run_supported": false, "output_schema_ref": "schemas/tools/ocr_default.analyze_document.output.json", "risk_class_default": "A", "required_permissions": ["Dokument zur Analyse uebermitteln"]}'::jsonb, '02ec67aa1dd8b3d81ee1f11c0eb2952654f64eb87003a35f3f0ab3bd726e7b78', 'spec/phase-1/jarvis-phase-1/registry/tool_registry_phase1.json', '2aea6dc8246e518e070f91480e890c2b7d76d538e6a6420ae4c5e1f3667d3621') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('llm_default.extract_fields', '1.0.0', 'llm_default', 'read', 'none', 'A', 'reversible', NULL, ARRAY['privat', 'arbeitgeber_visolva']::text[], false, ARRAY['provider_status']::text[], 'Der Nachweis belegt eine schemakonforme Modellantwort. Die fachliche Richtigkeit der Werte wird nicht belegt und ausschliesslich ueber Konfidenz-, Beleg- und Plausibilitaetsregeln bewertet.', 180, false, 'draft', '{"owner": "rolf", "purpose": "Aus Volltext und OCR-Kandidaten die Pflicht- und Zusatzfelder mit Konfidenz und Textbeleg gewinnen.", "tool_id": "llm_default.extract_fields", "version": "1.0.0", "evidence": {"limitation": "Der Nachweis belegt eine schemakonforme Modellantwort. Die fachliche Richtigkeit der Werte wird nicht belegt und ausschliesslich ueber Konfidenz-, Beleg- und Plausibilitaetsregeln bewertet.", "required_types": ["provider_status"], "accepted_methods": ["provider_status"], "readback_supported": false, "verify_delay_seconds": 0, "deferred_check_after_hours": null}, "operation": "read", "adapter_id": "llm_default", "rate_limit": null, "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": null, "native_support": false}, "display_name": "Felder auslesen", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "rate_limited", "timeout", "validation_error"]}, "side_effects": "Keine Veraenderung ausserhalb von JARVIS.", "undo_tool_id": null, "reversibility": "reversible", "external_effect": "none", "timeout_seconds": 180, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/tools/llm_default.extract_fields.input.json", "dry_run_supported": false, "output_schema_ref": "schemas/extraction_result.schema.json", "risk_class_default": "A", "required_permissions": ["Modellaufruf mit strukturierter Ausgabe"]}'::jsonb, '04d8785d8a7a1c23f93a16793dc86ed204db8e1cd05df88e3cbd09ed8f6626d6', 'spec/phase-1/jarvis-phase-1/registry/tool_registry_phase1.json', '2aea6dc8246e518e070f91480e890c2b7d76d538e6a6420ae4c5e1f3667d3621') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('llm_default.analyze_document', '1.0.0', 'llm_default', 'read', 'none', 'A', 'reversible', NULL, ARRAY['privat', 'arbeitgeber_visolva']::text[], false, ARRAY['provider_status']::text[], 'Der Nachweis belegt eine schemakonforme Modellantwort mit Textbelegen. Er belegt weder die Vollstaendigkeit der erkannten Verpflichtungen noch die Richtigkeit der Vorschlaege.', 240, false, 'draft', '{"owner": "rolf", "purpose": "Sachverhalt, Verpflichtungen, Moeglichkeiten, Risiken, Widersprueche, fehlende Angaben und Aufgabenvorschlaege bestimmen.", "tool_id": "llm_default.analyze_document", "version": "1.0.0", "evidence": {"limitation": "Der Nachweis belegt eine schemakonforme Modellantwort mit Textbelegen. Er belegt weder die Vollstaendigkeit der erkannten Verpflichtungen noch die Richtigkeit der Vorschlaege.", "required_types": ["provider_status"], "accepted_methods": ["provider_status"], "readback_supported": false, "verify_delay_seconds": 0, "deferred_check_after_hours": null}, "operation": "read", "adapter_id": "llm_default", "rate_limit": null, "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": null, "native_support": false}, "display_name": "Dokument verstehen", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "rate_limited", "timeout", "validation_error"]}, "side_effects": "Keine Veraenderung ausserhalb von JARVIS.", "undo_tool_id": null, "reversibility": "reversible", "external_effect": "none", "timeout_seconds": 240, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/tools/llm_default.analyze_document.input.json", "dry_run_supported": false, "output_schema_ref": "schemas/document_analysis.schema.json", "risk_class_default": "A", "required_permissions": ["Modellaufruf mit strukturierter Ausgabe"]}'::jsonb, '3d268e8a4d890ceda898ce6751b2508c73b37bee49da7c4b8fbc492c852d0617', 'spec/phase-1/jarvis-phase-1/registry/tool_registry_phase1.json', '2aea6dc8246e518e070f91480e890c2b7d76d538e6a6420ae4c5e1f3667d3621') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('docstore_internal.upsert_document', '1.0.0', 'docstore_internal', 'write', 'internal', 'A', 'reversible', NULL, ARRAY['privat', 'arbeitgeber_visolva']::text[], true, ARRAY['readback']::text[], NULL, 30, true, 'draft', '{"owner": "rolf", "purpose": "Dokumentdatensatz im Kontextschema anlegen oder fortschreiben.", "tool_id": "docstore_internal.upsert_document", "version": "1.0.0", "evidence": {"limitation": null, "required_types": ["state_readback"], "accepted_methods": ["readback"], "readback_supported": true, "verify_delay_seconds": 0, "deferred_check_after_hours": null}, "operation": "write", "adapter_id": "docstore_internal", "rate_limit": null, "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": "content_hash", "native_support": true}, "display_name": "Dokumentregister schreiben", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "timeout"]}, "side_effects": "Ein Dokumentdatensatz entsteht oder aendert seinen Zustand.", "undo_tool_id": null, "reversibility": "reversible", "external_effect": "internal", "timeout_seconds": 30, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/document.schema.json", "dry_run_supported": true, "output_schema_ref": "schemas/document.schema.json", "risk_class_default": "A", "required_permissions": ["Schreibrecht im Kontextschema"]}'::jsonb, '22653a59c5f22a552cbb4804b809a9b003bc093a00de2cfd86d18c2c419c53c9', 'spec/phase-1/jarvis-phase-1/registry/tool_registry_phase1.json', '2aea6dc8246e518e070f91480e890c2b7d76d538e6a6420ae4c5e1f3667d3621') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('casestore_internal.upsert_case', '1.0.0', 'casestore_internal', 'write', 'internal', 'A', 'reversible', NULL, ARRAY['privat', 'arbeitgeber_visolva']::text[], true, ARRAY['readback']::text[], NULL, 30, true, 'draft', '{"owner": "rolf", "purpose": "Vorgang mit Vorgangsnummer, Kennungen und Dokumentzuordnung im Kontextschema fuehren.", "tool_id": "casestore_internal.upsert_case", "version": "1.0.0", "evidence": {"limitation": null, "required_types": ["state_readback"], "accepted_methods": ["readback"], "readback_supported": true, "verify_delay_seconds": 0, "deferred_check_after_hours": null}, "operation": "write", "adapter_id": "casestore_internal", "rate_limit": null, "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": null, "native_support": true}, "display_name": "Vorgang anlegen oder fortschreiben", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "timeout"]}, "side_effects": "Ein Vorgang entsteht oder erhaelt ein weiteres Dokument.", "undo_tool_id": null, "reversibility": "reversible", "external_effect": "internal", "timeout_seconds": 30, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/case.schema.json", "dry_run_supported": true, "output_schema_ref": "schemas/case.schema.json", "risk_class_default": "A", "required_permissions": ["Schreibrecht im Kontextschema"]}'::jsonb, 'cbb5163c4914454ff19feef22bdb2abbc2c10d1e29128f60a8a35ea6c9cb4046', 'spec/phase-1/jarvis-phase-1/registry/tool_registry_phase1.json', '2aea6dc8246e518e070f91480e890c2b7d76d538e6a6420ae4c5e1f3667d3621') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('drafts_internal.create_draft', '1.0.0', 'drafts_internal', 'write', 'internal', 'A', 'reversible', 'drafts_internal.delete_draft', ARRAY['privat', 'arbeitgeber_visolva']::text[], true, ARRAY['readback']::text[], NULL, 60, true, 'draft', '{"owner": "rolf", "purpose": "Antwort-, Rueckfrage- oder Kuendigungsentwurf als Datei im Kontextspeicher ablegen. Kein Versand.", "tool_id": "drafts_internal.create_draft", "version": "1.0.0", "evidence": {"limitation": null, "required_types": ["file_ref"], "accepted_methods": ["readback"], "readback_supported": true, "verify_delay_seconds": 5, "deferred_check_after_hours": null}, "operation": "write", "adapter_id": "drafts_internal", "rate_limit": null, "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": "content_fingerprint", "native_support": false}, "display_name": "Entwurf erstellen", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "rate_limited", "timeout"]}, "side_effects": "Eine Entwurfsdatei entsteht im Kontextspeicher. Sie verlaesst das System nicht.", "undo_tool_id": "drafts_internal.delete_draft", "reversibility": "reversible", "external_effect": "internal", "timeout_seconds": 60, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/tools/drafts_internal.create_draft.input.json", "dry_run_supported": true, "output_schema_ref": "schemas/tools/drafts_internal.create_draft.output.json", "risk_class_default": "A", "required_permissions": ["Schreibrecht im Entwurfsordner des Kontexts"]}'::jsonb, '840f6d60d520f67313ae812877fda08eb007837e55f00e25b0ec345e8d2ef4fd', 'spec/phase-1/jarvis-phase-1/registry/tool_registry_phase1.json', '2aea6dc8246e518e070f91480e890c2b7d76d538e6a6420ae4c5e1f3667d3621') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('report_internal.write_daily_report', '1.0.0', 'report_internal', 'write', 'internal', 'A', 'reversible', NULL, ARRAY['privat', 'arbeitgeber_visolva']::text[], true, ARRAY['readback']::text[], NULL, 60, true, 'draft', '{"owner": "rolf", "purpose": "Abgeleitete Tagesuebersicht als Datei im Kontextspeicher erzeugen.", "tool_id": "report_internal.write_daily_report", "version": "1.0.0", "evidence": {"limitation": null, "required_types": ["file_ref"], "accepted_methods": ["readback"], "readback_supported": true, "verify_delay_seconds": 5, "deferred_check_after_hours": null}, "operation": "write", "adapter_id": "report_internal", "rate_limit": null, "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": null, "native_support": false}, "display_name": "Tagesbericht schreiben", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "rate_limited", "timeout"]}, "side_effects": "Eine Berichtsdatei entsteht oder wird ersetzt. Der Bericht ist eine abgeleitete Ansicht und niemals fuehrend.", "undo_tool_id": null, "reversibility": "reversible", "external_effect": "internal", "timeout_seconds": 60, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/tools/report_internal.write_daily_report.input.json", "dry_run_supported": true, "output_schema_ref": "schemas/tools/report_internal.write_daily_report.output.json", "risk_class_default": "A", "required_permissions": ["Schreibrecht im Berichtsordner des Kontexts"]}'::jsonb, 'd6bd763927f19b4105cc32c68058b9526e149a6aed5dda66ddeeddae3d2046db', 'spec/phase-1/jarvis-phase-1/registry/tool_registry_phase1.json', '2aea6dc8246e518e070f91480e890c2b7d76d538e6a6420ae4c5e1f3667d3621') ON CONFLICT (tool_id, version) DO NOTHING;
INSERT INTO jarvis_ops.tool_registry (tool_id, version, adapter_id, operation, external_effect, risk_class_default, reversibility, undo_tool_id, allowed_contexts, readback_supported, accepted_methods, evidence_limitation, timeout_seconds, dry_run_supported, status, definition, definition_sha256, source_file, source_sha256) VALUES ('test.record_approved_action', '1.0.0', 'test_internal', 'write', 'internal', 'C', 'reversible', NULL, ARRAY['privat', 'arbeitgeber_visolva']::text[], true, ARRAY['readback']::text[], NULL, 30, true, 'draft', '{"owner": "rolf", "purpose": "Ausschliesslich zum Nachweis des zweistufigen Klasse-C-Freigabewegs. Schreibt nach gueltiger Freigabe einen Testnachweis in einen abgegrenzten Testbereich des Kontextschemas.", "tool_id": "test.record_approved_action", "version": "1.0.0", "evidence": {"limitation": null, "required_types": ["state_readback"], "accepted_methods": ["readback"], "readback_supported": true, "verify_delay_seconds": 0, "deferred_check_after_hours": null}, "operation": "write", "adapter_id": "test_internal", "rate_limit": null, "idempotency": {"strategy": "db_unique_constraint", "key_fields": ["context_id", "source_ref", "action_type", "target_system", "target_object_ref"], "extra_dedup": "content_fingerprint", "native_support": true}, "display_name": "Testaktion mit Freigabe", "retry_policy": {"backoff": "exponential_1m_factor5_jitter", "max_attempts": 3, "retryable_error_classes": ["transient_network", "timeout"]}, "side_effects": "Ein Testdatensatz mit Aktions-ID, Freigabe-ID, Kontext, Zeitstempel und Ergebnisstatus entsteht. Keine Veraenderung an produktiven Dokumenten, keine externe Kommunikation.", "undo_tool_id": null, "reversibility": "reversible", "external_effect": "internal", "timeout_seconds": 30, "allowed_contexts": ["privat", "arbeitgeber_visolva"], "input_schema_ref": "schemas/tools/test.record_approved_action.input.json", "dry_run_supported": true, "output_schema_ref": "schemas/tools/test.record_approved_action.output.json", "risk_class_default": "C", "required_permissions": ["Schreibrecht in der Testtabelle des Kontextschemas"]}'::jsonb, '048f6a8a9e17e7f6f8faa1aa102209e89c8cc9a7e226ca840299d14cc3902cec', 'spec/phase-1/jarvis-phase-1/registry/tool_registry_phase1.json', '2aea6dc8246e518e070f91480e890c2b7d76d538e6a6420ae4c5e1f3667d3621') ON CONFLICT (tool_id, version) DO NOTHING;

-- Pruefung: Die Datenbank rechnet den Pruefwert aus der gespeicherten Definition nach.
DO $$
DECLARE
    v_bad text;
BEGIN
    SELECT string_agg(e.tool_id || '@' || e.version, ', ') INTO v_bad
    FROM (VALUES
        ('storage_gdrive.move_file', '1.0.0', '3b5c4ef233920e50fcd409d62ffca18bd67a610f0386b6e68e7cc66380c95f34'),
        ('tasks_internal.create_task', '1.0.0', '7f7ffd57979954afa94bb742f3958c65f7f9e46067d2b00907c02160e40fd1ac'),
        ('mail_default.send_message', '1.0.0', 'bddb2305ff17cf0f5f470d597ffd2fb8ac6e73f339655477525fc0effa50c4ea'),
        ('messaging_superchat.send_template_message', '1.0.0', '8cded196683889056b0a0fe4e8e52cfedfe16d6e1dca10f820ecdf9e4694caec'),
        ('approval_email.request_decision', '1.0.0', 'd259ab39ff01de0aa7a67f0f1ef4e6c48fceb5c8bc8af4ccb6b14ee5c5e8fc6d'),
        ('storage_gdrive.get_file', '1.0.0', '02372a67f50f263bd052c2e6ccc96b7e4853c49b290a95a3b7a3eed16717561b'),
        ('ocr_default.analyze_document', '1.0.0', '02ec67aa1dd8b3d81ee1f11c0eb2952654f64eb87003a35f3f0ab3bd726e7b78'),
        ('llm_default.extract_fields', '1.0.0', '04d8785d8a7a1c23f93a16793dc86ed204db8e1cd05df88e3cbd09ed8f6626d6'),
        ('llm_default.analyze_document', '1.0.0', '3d268e8a4d890ceda898ce6751b2508c73b37bee49da7c4b8fbc492c852d0617'),
        ('docstore_internal.upsert_document', '1.0.0', '22653a59c5f22a552cbb4804b809a9b003bc093a00de2cfd86d18c2c419c53c9'),
        ('casestore_internal.upsert_case', '1.0.0', 'cbb5163c4914454ff19feef22bdb2abbc2c10d1e29128f60a8a35ea6c9cb4046'),
        ('drafts_internal.create_draft', '1.0.0', '840f6d60d520f67313ae812877fda08eb007837e55f00e25b0ec345e8d2ef4fd'),
        ('report_internal.write_daily_report', '1.0.0', 'd6bd763927f19b4105cc32c68058b9526e149a6aed5dda66ddeeddae3d2046db'),
        ('test.record_approved_action', '1.0.0', '048f6a8a9e17e7f6f8faa1aa102209e89c8cc9a7e226ca840299d14cc3902cec')
    ) AS e (tool_id, version, sha)
    LEFT JOIN jarvis_ops.tool_registry t ON t.tool_id = e.tool_id AND t.version = e.version
    WHERE t.definition_sha256 IS DISTINCT FROM e.sha
       OR encode(sha256(convert_to(t.definition::text, 'UTF8')), 'hex') IS DISTINCT FROM e.sha
       OR t.tool_id            IS DISTINCT FROM t.definition->>'tool_id'
       OR t.version            IS DISTINCT FROM t.definition->>'version'
       OR t.adapter_id         IS DISTINCT FROM t.definition->>'adapter_id'
       OR t.operation          IS DISTINCT FROM t.definition->>'operation'
       OR t.external_effect    IS DISTINCT FROM t.definition->>'external_effect'
       OR t.risk_class_default::text IS DISTINCT FROM t.definition->>'risk_class_default'
       OR t.reversibility      IS DISTINCT FROM t.definition->>'reversibility'
       OR t.undo_tool_id       IS DISTINCT FROM t.definition->>'undo_tool_id'
       OR t.timeout_seconds    IS DISTINCT FROM (t.definition->>'timeout_seconds')::int
       OR t.dry_run_supported  IS DISTINCT FROM (t.definition->>'dry_run_supported')::boolean
       OR t.readback_supported IS DISTINCT FROM (t.definition->'evidence'->>'readback_supported')::boolean
       OR t.evidence_limitation IS DISTINCT FROM t.definition->'evidence'->>'limitation'
       OR t.allowed_contexts   IS DISTINCT FROM ARRAY(SELECT jsonb_array_elements_text(t.definition->'allowed_contexts'))
       OR t.accepted_methods   IS DISTINCT FROM ARRAY(SELECT jsonb_array_elements_text(t.definition->'evidence'->'accepted_methods'));
    IF v_bad IS NOT NULL THEN
        RAISE EXCEPTION 'registry_definition_mismatch: %', v_bad USING ERRCODE = '23514';
    END IF;
END
$$;
